//export reducer home
export const REQUEST_GET_DAYOFF = "REQUEST_GET_DAYOFF";
export const REQUEST_GET_DISDAYOFF = "REQUEST_GET_DISDAYOFF";
export const REQUEST_DELETE_DAYOFF = "REQUEST_DELETE_DAYOFF";
export const REQUEST_ADD_DAYOFF = "REQUEST_ADD_DAYOFF";
export const REQUEST_UPDATE_DAYOFF = "REQUEST_UPDATE_DAYOFF";
//export reducer user
export const REQUEST_GET_USER = "REQUEST_GET_USER";
export const REQUEST_DELETE_USER = "REQUEST_DELETE_USER";
export const REQUEST_ADD_USER = "REQUEST_ADD_USER";
export const REQUEST_UPDATE_USER = "REQUEST_UPDATE_USER";
//export reducer user
export const REQUEST_GET_LEAD = "REQUEST_GET_LEAD";
export const REQUEST_GET_MAIL = "REQUEST_GET_MAIL";
//export reducer login 
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGUOT = "REQUEST_LOGUOT";
//export reducer team
export const ADD_TEAM = "ADD_TEAM";
export const GET_TEAM = "GET_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const UPDATE_TEAM = "UPDATE_TEAM";
//export reducer position
export const ADD_POSITION = "ADD_POSITION";
export const GET_POSITION = "GET_POSITION";
export const DELETE_POSITION = "DELETE_POSITION";
export const UPDATE_POSITION = "UPDATE_POSITION";
//export reducer registration
export const GET_REGISTRATION = "GET_REGISTRATION";
//export reducer type dayoff
export const REQUEST_GET_TYPEDAYOFF = "REQUEST_GET_TYPEDAYOFF";
export const REQUEST_DELETE_TYPEDAYOFF = "REQUEST_DELETE_TYPEDAYOFF";
export const REQUEST_ADD_TYPEDAYOFF = "REQUEST_ADD_TYPEDAYOFF";
export const REQUEST_UPDATE_TYPEDAYOFF  = "REQUEST_UPDATE_TYPEDAYOFF";
export const REQUEST_SEARCH  = "REQUEST_SEARCH";
export const REQUEST_SEARCH_APPROVED  = "REQUEST_SEARCH_APPROVED";
export const REQUEST_LIST_QUEUE = "REQUEST_LIST_QUEUE";
export const REQUEST_LIST_ACCEPT = "REQUEST_LIST_ACCEPT";
export const REQUEST_UPDATE_ACCEPT = "REQUEST_UPDATE_ACCEPT";
export const REQUEST_SEND_ACCEPT = "REQUEST_SEND_ACCEPT";
export const REQUEST_UPDATE_DISACCEPT = "REQUEST_UPDATE_DISACCEPT";
export const REQUEST_LIST_DISACCEPT = "REQUEST_LIST_DISACCEPT";
export const REQUEST_SEARCH_DISAPPROVED = "REQUEST_SEARCH_DISAPPROVED";
export const REQUEST_SEARCH_QUEUEACCEPT ="REQUEST_SEARCH_QUEUEACCEPT";
//export reducer admin
export const ADD_STORE = "ADD_STORE";
export const GET_STORE = "GET_STORE";
export const DELETE_STORE = "DELETE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
