//export reducer home
export const REQUEST_GET_DAYOFF = "REQUEST_GET_DAYOFF";
export const REQUEST_DELETE_DAYOFF = "REQUEST_DELETE_DAYOFF";
export const REQUEST_ADD_DAYOFF = "REQUEST_ADD_DAYOFF";
export const REQUEST_UPDATE_DAYOFF = "REQUEST_UPDATE_DAYOFF";
//export reducer user
export const REQUEST_GET_USER = "REQUEST_GET_USER";
export const REQUEST_DELETE_USER = "REQUEST_DELETE_USER";
export const REQUEST_ADD_USER = "REQUEST_ADD_USER";
export const REQUEST_UPDATE_USER = "REQUEST_UPDATE_USER";
//export reducer user
export const REQUEST_GET_LEAD = "REQUEST_GET_LEAD";
//export reducer login 
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGUOT = "REQUEST_LOGUOT";
//export reducer type dayoff
export const REQUEST_GET_TYPEDAYOFF = "REQUEST_GET_TYPEDAYOFF";
export const REQUEST_DELETE_TYPEDAYOFF = "REQUEST_DELETE_TYPEDAYOFF";
export const REQUEST_ADD_TYPEDAYOFF = "REQUEST_ADD_TYPEDAYOFF";
export const REQUEST_UPDATE_TYPEDAYOFF  = "REQUEST_UPDATE_TYPEDAYOFF";
export const REQUEST_SEARCH  = "REQUEST_SEARCH";
export const REQUEST_LIST_QUEUE = "REQUEST_LIST_QUEUE";
export const REQUEST_LIST_ACCEPT = "REQUEST_LIST_ACCEPT";
export const REQUEST_UPDATE_ACCEPT = "REQUEST_UPDATE_ACCEPT";